name: app_chat
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  image_picker: ^1.1.1
  permission_handler: ^11.3.1
  sqflite: ^2.3.3
  path: ^1.9.0
  intl: ^0.19.0
  http: ^1.2.1
  connectivity_plus: ^6.0.3
  universal_io: ^2.2.2
  http_parser: ^4.0.2
  emoji_picker_flutter: ^2.2.0
  foundation: ^0.0.5
  photo_manager: ^3.1.1
  multi_image_picker2: ^5.0.02
  path_provider: ^2.1.3
  file_picker: ^8.0.3
  crypto: ^3.0.3
  flutter_local_notifications: ^17.1.2
  encrypt: ^5.0.3
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  bloc: ^8.1.4
  flutter_localization: ^0.2.0
  injectable: ^2.4.4
  dartz: ^0.10.1
  get_it: ^7.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner:
  injectable_generator:

flutter:

  uses-material-design: true
  assets:
    - lib/core/assets/images/
flutter_intl:
  enabled: true
